#! /usr/bin/python
import subprocess, sys
from tempfile import NamedTemporaryFile

fname = ""
with TemporaryFile(delete=False) as _file:
    file_.write(sys.strin.read())    
    fname = file_.name

result = subprocess.call("./slct2 " + fname, sys.argv, stdout=open('/dev/tty', 'w'), stdin=open('/dev/tty', 'r'), stderr=open('/dev/tty', 'w'))

if result > 0:
    with open(fname) as _file:
        sys.stdout.write(_file.read())
        _file.write("")
else:
    sys.exit(result)
