#! /usr/bin/env python3
import subprocess, sys
from tempfile import NamedTemporaryFile

fname = ""
with NamedTemporaryFile(delete=False) as _file:
    _file.write(bytes(sys.stdin.read(), 'UTF-8'))
    fname = _file.name


col = "0"
sep = " "
if len(sys.argv) > 1: col = sys.argv[1]
if len(sys.argv) > 2: sep = sys.argv[2]

result = subprocess.call(
    ["slct.py", fname, col, sep, fname]
    , stdin=open('/dev/tty', 'r')
    , stderr=open('/dev/tty', 'w')
    , stdout=open('/dev/tty', 'w')
)

if result < 1:
    with open(fname, "r") as _file:
        sys.stdout.write(_file.read())
    with open(fname, "w") as _file:
        _file.write("")
else:
    sys.exit(result)
